server:
  port: 8080


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: serurity-service
          uri: http://localhost:8084
          predicates:
            - Path=/**
    loadbalancer:
      ribbon:
        enabled: true


hystrix:
  command:
    HystrixConfig:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost