server:
  port: ${port:8080}



spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #lowerCaseServiceId: true
      routes:
        - id: security-service
          uri: http://localhost:8084
          # uri: lb://SECURITY-SERVICE - works but redirecting to xx.
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-service
                fallbackuri: forward:/securityservicefallback
      metrics:
        enabled: true


eureka:
  instance:
    instance-id: cloud-gateway-service


resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 10
      sliding-window-type: COUNT_BASED
      minimum-number-of-calls: 5
      writable-stack-trace-enabled: true
      permitted-number-of-calls-in-half-open-state: 2
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 50
  instances:
    security-service:
      baseConfig: default


management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    refresh:
      enabled: true


info:
  app:
    name: microservice application
    description: cloud-gateway service
    version: 1.0.0


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
  file:
    name: logs/cloud-gateway-log.txt