server:
  port: 8080


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:8084
          predicates:
            - Path=/**

    loadbalancer:
      ribbon:
        enabled: false


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
  file:
    name: logs/cloudgateway-log.txt


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost